# Generated by Django 4.2.3 on 2023-07-25 02:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('survey_app', '0003_answer_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='survey',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='survey',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
