# Generated by Django 4.2.3 on 2023-07-31 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey_app', '0007_alter_answer_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='survey',
            options={'permissions': [('can_update_survey', 'Can update survey')]},
        ),
    ]
